plugins {
  id 'com.github.ben-manes.versions' version '0.54.0'
  id 'scala'
  id 'application'
  id 'maven-publish'
  id 'signing'
  id 'org.podval.tools.scalajs' version '1.0.3'
//  id 'com.gradleup.nmcp.aggregation' version '1.4.0'
}

description = 'Generate, serve and publish websites'
group = 'org.podval.tools'
version = '0.0.1'

java.toolchain.languageVersion = JavaLanguageVersion.of(21)
scala.scalaVersion = '3.8.4'
project.gradle.startParameter.excludedTaskNames.add('compileJava')

String zioBlocksVersion = '0.0.47'
String flexMarkVersion = '0.64.8'

dependencies {
  implementation "dev.zio:zio-blocks-schema-xml_3:$zioBlocksVersion"
  implementation "dev.zio:zio-blocks-schema-yaml_3:$zioBlocksVersion"
  implementation "dev.zio:zio-blocks-html_3:$zioBlocksVersion"
  implementation 'org.ccil.cowan.tagsoup:tagsoup:1.2.1'
  implementation "com.vladsch.flexmark:flexmark:$flexMarkVersion"
  implementation "com.vladsch.flexmark:flexmark-ext-autolink:$flexMarkVersion"
  implementation "com.vladsch.flexmark:flexmark-ext-footnotes:$flexMarkVersion"
  implementation "com.vladsch.flexmark:flexmark-ext-gfm-strikethrough:$flexMarkVersion"
  implementation "com.vladsch.flexmark:flexmark-ext-gfm-tasklist:$flexMarkVersion"
  implementation "com.vladsch.flexmark:flexmark-ext-tables:$flexMarkVersion"
  implementation 'org.typelevel:paiges-core_3:0.4.4'
  implementation 'org.asciidoctor:asciidoctorj:3.0.0'
  implementation 'org.eclipse.jgit:org.eclipse.jgit:7.7.0.202606012155-r'
  implementation 'org.slf4j:slf4j-api:2.0.18'
  implementation 'ch.qos.logback:logback-classic:1.5.38'
  compileOnly 'net.logstash.logback:logstash-logback-encoder:9.0'
  testImplementation 'dev.zio:zio-test-sbt_3:2.1.26'
}

application {
  mainClass = 'org.podval.tools.publish.site.Site'
}

def isNonStable = { String version ->
  boolean stableKeyword = ['RELEASE', 'FINAL', 'GA'].any { it -> version.toUpperCase().contains(it) }
  String regex = /^[0-9,.v-]+(-r)?$/
  return !stableKeyword && !(version ==~ regex)
}

tasks.named("dependencyUpdates").configure {
  rejectVersionIf {
    isNonStable(it.candidate.version)
  }
}

tasks.withType(ScalaCompile).configureEach {
  scalaCompileOptions.with {
    additionalParameters = [
      '-new-syntax',
      '-feature',
      '-language:strictEquality',
      '-source:future'
    ]
  }
}

jar {
  manifest {
    attributes(
      'Implementation-Title'  : project.description,
      'Implementation-Version': project.version
    )
  }
}

tasks.register('sourcesJar', Jar) {
  from sourceSets.main.allSource
  archiveClassifier.set('sources')
}

tasks.register('scaladocJar', Jar) {
  from scaladoc.destinationDir
  archiveClassifier.set('scaladoc')
}
scaladocJar.dependsOn scaladoc

// There is no Java in the project, but Maven Central requires javadoc JAR...
tasks.register('javadocJar', Jar) {
  from javadoc.destinationDir
  archiveClassifier.set('javadoc')
}
javadocJar.dependsOn(javadoc)

final String gitHubRepository = "dubinsky/publisher"
final String gitHubRepositoryUrl = "https://github.com/$gitHubRepository"
final String orgName = 'Podval Group'
final String orgUrl = 'https://www.podval.org'

publishing {
  publications {
    library(MavenPublication) {
      from components.java
      artifact sourcesJar
      artifact scaladocJar
      artifact javadocJar

      pom {
        name = project.name
        description = project.description
        url = gitHubRepositoryUrl
        scm {
          url = gitHubRepositoryUrl
          connection = "scm:git:git://github.com/${gitHubRepository}.git"
          developerConnection = "scm:git:ssh://github.com/${gitHubRepository}.git"
        }
        licenses {
          license {
            name = 'The Apache Software License, Version 2.0'
            url = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
            distribution = 'repo'
            comments = 'A business-friendly OSS license'
          }
        }
        organization {
          name = orgName
          url = orgUrl
        }
        developers {
          developer {
            id = 'dub'
            name = 'Leonid Dubinsky'
            email = 'dub@podval.org'
            url = 'https://dub.podval.org'
            organization = orgName
            organizationUrl = orgUrl
            timezone = '-5'
          }
        }
      }
    }
  }
}

signing {
  sign publishing.publications.library
  useInMemoryPgpKeys(
    findProperty('signingKey') as String,
    findProperty('signingPassword') as String
  )
}

// ./gradlew nmcpZipAggregation - to see what will be published
// ./gradlew publishAggregationToCentralPortal - to publish
// https://central.sonatype.com/publishing/deployments - to release
//nmcpAggregation {
//  centralPortal {
//    publishingType = "USER_MANAGED"
//    username = findProperty('mavenCentralUsername') as String
//    password = findProperty('mavenCentralPassword') as String
//  }
//}
//
//tasks.register('uploadLibrary')
//uploadLibrary.description = 'Upload artifacts'
//uploadLibrary.group = 'publishing'
//uploadLibrary.dependsOn(publishAggregationToCentralPortal)
//
//tasks.register('upload')
//upload.description = 'Upload artifacts and plugins'
//upload.group = 'publishing'
//upload.dependsOn(uploadLibrary)
//upload.dependsOn(publishPlugins)
