= Static Site Publisher
:toc:
:toclevels: 4
:toc: preamble
:icons: font

Generate and publish websites.

[#summary]
== Summary

== Opinionated

Since I am writing this site generator for my own use,
it is going to be opinionated:

- everything is written in Scala
- no plugins
- no SCSS
- no template languages
- no layouts

TODO expound

[#features]
== Features

=== Titles and File Names
Jekyll relies on page titles being given explicitly in the front matter
and ignores the file names; I had to use a TODO Obsidian plugin to set the
titles from the file names to communicate them to Jekyll;
as a result, pages where the title is different from the file name
(e.g., `index` pages)
had to be marked with TODO in their front matter to disable this plugin
from setting the front matter title.

My plugin uses both the front matter title and the file name for
link resolution, so I can remove this Obsidian plugin and
redundant front matter titles which are the same as the file name,
and set the title in the front matter only when it is different from the file name.

Obsidian uses file names exclusively and ignores the front matter title;
for link resolution to use front matter titles also,
TODO Obsidian plugin needs to be installed.

Wiki links in Obsidian:

- are they case-sensitive?
- do they take into account file name, title property, document title?
- how do they look in the file if name reference is ambiguous?
- can they be split between the lines?
- do they support any kind of agglutination?

=== Notes and Posts

- home page: directory
- directory structure
- auto-post (same file name)
- permalink (any file name)

=== Markdown extensions
Site generator supports Markdown tables via FlexMark Tables Extension;
Obsidian supports them natively.

Site generator supports Markdown task lists via FlexMark Task List Extension;
Obsidian supports them natively.

== Farewell, Jekyll

Events of 2026:

- Mar 17: My Jekyll setup (wiki-refs plugin) broke down
- Mar 20: I created my site publisher repository
- I became aware of ZIO Blocks Yaml released on Mar 11 and ZIO Blocks Markdown released on Jan 30
- Mar 22: I filed ZIO Blocks pull request
- Apr 30: I switched my personal website to use my site publisher vis GitHub Actions Workflow
- May 04: I removed all traces of Jekyll from my personal website
- May 06: I became aware of the ZIO Blocks HTML that was added on Apr 25-May 01, and started switching to it from my home-grown HTML DSL
- May 07: switched


First milestone for this project is to replace Jekyll on my personal website.
In under two month and a little less than 2000 lines of Scala code,
I have:

- no support for paginating the post list, which I did not use with Jekyll anyway;
- instead of the Ruby code highlighter Rouge, my publisher uses Highlights.js; it loads only the language modules used in the page; TODO unsupported language mapping...

- while I did manage to list children pages using Jekyll,
I never figured out how to list subdirectories;
with my own publisher this is not a problem ;)

- Jekyll ignores Markdown files without front matter; I do not;
- wiki links
- link resolution
- front-matter defaults auto-added pages;
- header pages are configured in their frontmatter, with FA icons (and defaults) ;)
- transclusion
- directory navigation: up, prev, next;
- path navigation;
- insertion of missing index pages;

Write about all the plugins I used:

- jekyll-optional-front-matter
- jekyll-sitemap
- jekyll-feed
- jekyll-mentions
- jekyll-avatar
- jekyll-wikirefs

[#future]
== Future

=== TEI

- metadata (including title) from the document itself
- footnotes should cling to preceding elements, not just text
- facsimiles
- raw TEI

=== Pages
- do PDF embedding - with `<object>`, `<iframe>` or?
- do video embedding?
- recognize more audio/image types;
- treat `<img>` as a link element also?
- sort the pages in transclusion order, extract sections and blocks,  transclude, and style the transclusions
- generate RSS feed
- add whatever is needed for the feed to the `<head>`
- implement SEO - or is just the page title in the `<head>` all I need?
- whatever the feed post summaries end up being, conditionally add same as post excerpt to the post list
- generate error report page(s):
* broken links
* inconsistent titles
- handle categories; they can be wiki links?!
- auto-create category pages
- auto-create tag pages

=== Chunking and Paging
- implement splitting of HTML by section when front matter has `chunk: true`
- implement paging of the long lists (e.g., list of posts)
- generate PDF when front-matter says `pdf: true`
* danfickle/openhtmltopdf: An HTML to PDF library for the JVM. Based on Flying Saucer and Apache PDF-BOX 2. With SVG image support. Now also with accessible PDF support (WCAG, Section 508, PDF/UA)! · GitHub[https://share.google/UiGeZVUcInZur8zNF](https://share.google/UiGeZVUcInZur8zNF)
* [https://gist.github.com/rjozefowicz/fa0618fce8e6ae28ff5c46b65ba7defd](https://gist.github.com/rjozefowicz/fa0618fce8e6ae28ff5c46b65ba7defd)

=== More Markup Languages

- AsciiDoc

- DocBook??
- ReStructured Text?

=== CLI
- package as a GitHub Action
- serve with filesystem watch
- publish site into a bucket

=== Further Research

- add publishing and updating a page to X once X API supports Articles
- add admonitions/asides/callouts support in a way that works for both FlexMark and Obsidian.
- Look at https://stephango.com/vault
- Look at https://squidfunk.github.io/mkdocs-material/
- Look at https://github.com/KaTeX/KaTeX[KaTeX] as a MathJax alternative...
- Think about serializing the full list of back-links out of the memory
- Maybe use FlexMark to convert wiki-links without resolving them (and lose support for wiki links in TEI)
- Maybe configure FlexMark to not convert general transclusion Markdown links (if it does now)

[#motivation]
== Motivation

=== Jekyll finally pissed me off

When I listed TODO link  unresistable to any programmer urge to
write certain kinds of systems, I neglected to mention
a static site generator.

I've been using Jekyll since I migrated my blog from Blogger TODO when;
I then moved my notes from Roam into Obsidian
TODO when link and merged them into the static site with my blog;
that required customizing my Jekyll setup
TODO move Jekyll customization notes into the Jekyll page and link it here.

In March 2026, my site stopped publishing;
error messages were meaningless, and it took a lot of time
to figure out what is the problem by deleting files until it went away.
It turned out that Jekyll plugin I used for handling wiki links TODO link
breaks when an `index` page contains a wiki link (e.g., a [[TODO]]).
Previous communications with the author of the plugin made it clear
that he considers Jekyll to be a legacy system
(but it remained unclear what is the suggested replacement).

At this point, I looked at a few of the modern static site generators
like 11ty TODO link - and decided to write my own ;)

=== New Possibilities

It occurred to me that if I write my own site generator,
I can make it Obsidian-aware:

- it can read Obsidian configuration
- it can publish daily notes as dated blog posts

It also occurred to me that I can make alter-rebbe.org TODO link,
a site where I publish some archive documents in the TEI format
static (again) -
if I add support for TEI to my generator:

- link resolution
- facsimiles
- multi-lingual names

It also occurred to me that I can add publishing to X Articles -
if X ever makes an API for that. This would allow me
to own my blog - and at the same time use X ;)
