package org.podval.tools.publish.markup

import org.podval.tools.publish.page.PageSource
import org.podval.tools.publish.site.Site
import org.podval.xml.{HtmlXmlDialect, Xml}
import zio.blocks.chunk.Chunk
import java.io.File

object HtmlMarkup extends Markup(
  name = "HTML",
  allowsInternalFrontMatter = true,
  extension = "html",
  rendersToXml = false,
  xmlDialect = HtmlXmlDialect,
):
  def headerLevel(element: Xml.Element): Option[Int] =
    val qName: String = element.getName
    if !qName.startsWith("h") then None else
      try Some(qName.substring(1).toInt)
      catch case _: NumberFormatException => None

  override def xmlContent(content: String, sourceFile: File, site: Site): String =
    // Wrap HTML in a 'div' to accommodate multi-root documents.
    s"<div>$content</div>"

  override def process(
    source: PageSource,
    xml: Xml.Element
  ): (Xml.Element, Option[Xml.Element]) =
    val (result: Xml.Element, title: Option[Xml.Element]) = xml
      .getChildren
      .flatMap(_.asElement)
      .find(element => headerLevel(element).contains(1))
      .fold((xml, None)): h1 =>
        (xml.setChildren(xml.getChildren.filterNot(_ eq h1)), Some(h1))

    // Nest HTML sections once the title ('h1') is removed.
    val nested: Xml.Element = result.setChildren(nestSections(result.getChildren))

    (nested, title)

  // Wrap each HTML section at the top level in a 'div' with class 'section'.
  // Transplant id from the header element to the section element;
  // generate the id if none is present.

  // Note: for Markdown, ids can be auto-generated by setting `HtmlRenderer.GENERATE_HEADER_ID`;
  // for AsciiDoc, by setting `sectids` attribute to `true` -
  // but I do it manually and uniformly for HTML, Markdown, etc.

  // Sections are represented by the HTML `h` elements and are not nested.
  // Common for markup formats whose XML representation is actually HTML:
  // HTML itself, Markdown, AsciiDoc, and likely Re-Structured text;
  // pure XML markup formats like TEI and DocBook are different.

  // From:
  //   <h2 id="colophon">Colophon</h2>
  //   <p>...</p>
  // To:
  //   <div class="section" id="colophon">
  //     <h2>Colophon</h2>
  //     <p>...</p>
  //   </div>
  private def nestSections(nodes: Xml.Nodes): Xml.Nodes =
    val headerLevels: Chunk[Int] = nodes.flatMap(_.asElement).flatMap(HtmlMarkup.headerLevel)
    if headerLevels.isEmpty then nodes else
      val headerLevel: Int = headerLevels.head
      val (preamble: Xml.Nodes, rest: Xml.Nodes) = nodes.span(
        _.asElement.fold(true)(HtmlMarkup.headerLevel(_).isEmpty)
      )
      val header: Xml.Element = rest.head.asElement.get
      val (body: Xml.Nodes, tail: Xml.Nodes) = rest.tail.span(
        _.asElement.fold(true)(HtmlMarkup.headerLevel(_).fold(true)(_ > headerLevel))
      )
      val section: Xml.Element = Section.mark(Xml.element("div"))
        .setId(header.getId)
        .setChildren(Chunk(header.setId("")) ++ nestSections(body))

      preamble ++ Chunk(section) ++ nestSections(tail)
