package org.podval.tools.publish.html

import org.podval.tools.publish.link.Section
import org.podval.tools.publish.markup.Transformer
import org.podval.tools.publish.util.IdGenerator
import org.podval.xml.Xml
import zio.blocks.chunk.Chunk

// Wrap each HTML section at the top level in a 'div' with class 'section'.
// Transplant id from the header element to the section element;
// generate the id if none is present.

// Note: for Markdown, ids can be auto-generated by setting `HtmlRenderer.GENERATE_HEADER_ID`;
// for AsciiDoc, by setting `sectids` attribute to `true` -
// but I do it manually and uniformly for HTML, Markdown, etc.

// Sections are represented by the HTML `h` elements and are not nested.
// Common for markup formats whose XML representation is actually HTML:
// HTML itself, Markdown, AsciiDoc, and likely Re-Structured text;
// pure XML markup formats like TEI and DocBook are different.

// Before:
//   <h2 id="colophon">Colophon</h2>
//   <p>...</p>
//
// After:
//   <div class="section" id="colophon">
//     <h2>Colophon</h2>
//     <p>...</p>
//   </div>
final class HtmlSectionsTransformer(ids: IdGenerator) extends Transformer:
  override def transform(element: Xml.Element): Xml.Element =
    element.setChildren(transform(element.getChildren))
 
  private def transform(nodes: Xml.Nodes): Xml.Nodes =
    val headerLevels: Chunk[Int] = nodes.flatMap(_.asElement).flatMap(HtmlMarkup.headerLevel)
    if headerLevels.isEmpty then nodes else
      val headerLevel: Int = headerLevels.head
      val (preamble: Xml.Nodes, rest: Xml.Nodes) = nodes.span(
        _.asElement.fold(true)(HtmlMarkup.headerLevel(_).isEmpty)
      )
      val header: Xml.Element = rest.head.asElement.get
      val (body: Xml.Nodes, tail: Xml.Nodes) = rest.tail.span(
        _.asElement.fold(true)(HtmlMarkup.headerLevel(_).fold(true)(_ > headerLevel))
      )
      val section: Xml.Element = Xml
        .element("div")
        .add(Section.SectionClass)
        .setId(header.getId.getOrElse(ids.general()))
        .setChildren(Chunk(header.setId("")) ++ transform(body))
      
      preamble ++ Chunk(section) ++ transform(tail)
