package org.podval.tools.publish.site

import org.apache.pdfbox.Loader
import org.apache.pdfbox.text.PDFTextStripper
import org.podval.tools.publish.util.{Files, PdfNamedDestinations, SiteOptions}
import org.scalatest.BeforeAndAfterAll
import org.scalatest.funsuite.AnyFunSuite
import java.io.File

final class SiteSpec extends AnyFunSuite, BeforeAndAfterAll:
  private val repositoryRoot: File =
    val anchor = getClass.getResource("/anchor.txt")
    require(anchor != null, "missing test resource /anchor.txt")
    File(anchor.toURI)
      .getParentFile // resources
      .getParentFile // test
      .getParentFile // src
      .getParentFile // root

  private val sourceDirectory: File = File(repositoryRoot, "src/test/site")
  private val targetDirectory: File = File(repositoryRoot, "build/test-site")

  override def beforeAll(): Unit =
    super.beforeAll()
    Site(SiteOptions(
      sourceDirectoryPath = sourceDirectory.getAbsolutePath,
      targetDirectoryNameOpt = Some(targetDirectory.getAbsolutePath),
      treatErrorsAsWarnings = true,
      logLevelOpt = Some("WARN")
    )).generate()

  private def html(relative: String): String =
    val file: File = File(targetDirectory, relative)
    assert(file.isFile, s"missing $relative under $targetDirectory")
    Files.read(file).replaceAll("\\s+", " ").replace("= ", "=")

  private def exists(relative: String): Unit =
    assert(File(targetDirectory, relative).isFile, s"missing $relative under $targetDirectory")

  test("generates into build/test-site, not _site under the fixture") {
    assert(targetDirectory.isDirectory, targetDirectory)
    assert(targetDirectory.getAbsolutePath.contains(s"${File.separator}build${File.separator}test-site"))
    assert(!File(sourceDirectory, "_site").exists)
  }

  test("writes synthetic pages, CSS, sitemap, robots, and feed") {
    exists("index.html")
    exists("errors.html")
    exists("tags.html")
    exists("posts.html")
    exists("sitemap.xml")
    exists("robots.txt")
    exists("feed.xml")
    exists("assets/css/style.css")
  }

  test("home page wiki links resolve") {
    val page: String = html("index.html")
    assert(page.contains("Site Publisher Fixture"), page)
    assert(page.contains("""href="/notes.html""""), page)
    assert(page.contains("""href="/glossary.html""""), page)
    assert(page.contains("""href="/cite.html""""), page)
    assert(page.contains("""href="/chunked.html""""), page)
    assert(page.contains("""href="/chunked/index.html""""), page)
    assert(page.contains("""href="/book.html""""), page)
    assert(page.contains("""href="/about.html""""), page)
    assert(page.contains("""href="/tei-sample.html""""), page)
    assert(page.contains("""href="/docbook-sample.html""""), page)
    assert(!page.contains("unresolved-link"), page)
  }

  test("Markdown notes: table, task-list IR, footnotes, fenced scala") {
    val page: String = html("notes.html")
    assert(page.contains("<table"), page)
    assert(page.contains(">1</td>") || page.contains(">1</th>") || page.contains(">1<"), page)
    assert(page.contains("""class="task-list""""), page)
    assert(page.contains("""class="task-list-item""""), page)
    assert(page.contains("task-list-item-checkbox"), page)
    assert(page.contains("open the box"), page)
    assert(page.contains("done already"), page)
    assert(page.contains("""class="footnote-ref""""), page)
    assert(page.contains("""class="footnote-tip""""), page)
    assert(page.contains("Markdown footnote body"), page)
    assert(page.contains("""</strong><span class="footnote-ref""""), page)
    assert(page.contains("""class="footnotes""""), page)
    assert(page.contains("language-scala"), page)
    assert(page.contains("xs.map(f)"), page)
    assert(page.contains("""class="admonition""""), page)
    assert(page.contains("""data-type="tip""""), page)
    assert(page.contains("Save time"), page)
    assert(page.contains("""class="aside""""), page)
    assert(page.contains("From Markdown"), page)
    assert(page.contains("""class="quote""""), page)
    assert(page.contains("A Markdown quotation"), page)
    assert(page.contains("<del"), page)
    assert(page.contains("struck out"), page)
    assert(page.contains("""class="figure""""), page)
    assert(page.contains("pixel.svg"), page)
    assert(page.contains("A Markdown figure"), page)
    assert(page.contains("""class="pdf-embed""""), page)
    assert(page.contains("sample.pdf"), page)
    assert(page.contains("""type="application/pdf""""), page)
    assert(page.contains("<video"), page)
    assert(page.contains("clip.mp4"), page)
    assert(page.contains("unresolved-link"), page)
    assert(page.contains("missing-page"), page)
    assert(page.contains("""class="backlinks""""), page)
    exists("notes-alias.html")
    val alias: String = html("notes-alias.html")
    assert(alias.contains("/notes.html"), alias)
    assert(alias.toLowerCase.contains("refresh"), alias)
    val errors: String = html("errors.html")
    assert(errors.contains("unresolved"), errors)
    assert(errors.contains("missing-page"), errors)
  }

  test("Markdown glossary IAL yields term ids and hover tips") {
    val page: String = html("glossary.html")
    assert(page.contains("""class="glossary""""), page)
    assert(page.contains("""class="glossary-item""""), page)
    assert(page.contains("""id="posuk""""), page)
    assert(page.contains("""class="glossary-ref""""), page)
    assert(page.contains("""class="glossary-tip""""), page)
    assert(page.contains("a verse"), page)
  }

  test("Markdown APA cites become #bibl- links; unknown keys are recorded") {
    val page: String = html("cite.html")
    assert(page.contains("""href="#bibl-knuth79""""), page)
    assert(page.contains("""id="bibl-knuth79""""), page)
    assert(page.contains("""id="bibl-lamport94""""), page)
    assert(page.contains("Knuth") || page.toLowerCase.contains("knuth"), page)
    assert(page.contains("unresolved-citation"), page)
    assert(page.contains("missing-key"), page)
    val errors: String = html("errors.html")
    assert(errors.contains("unknown citation"), errors)
    assert(errors.contains("missing-key"), errors)
    assert(!File(targetDirectory, "library.bib").exists, "library.bib must not be published")
    assert(!File(targetDirectory, "_bibliography.bib").exists)
  }

  test("chunked Markdown writes a TOC chunk and per-section pages") {
    exists("chunked.html")
    val toc: String = html("chunked/index.html")
    assert(toc.contains("Preamble of the chunked document"), toc)
    assert(toc.contains("Table of Contents"), toc)
    assert(!toc.contains("Alpha preamble, before subsections"), toc)
    assert(!toc.contains("""class="directory""""), toc)
    assert(!File(targetDirectory, "chunked/chunked.html").exists)
    val alpha: String = html("chunked/Alpha.html")
    assert(alpha.contains("Alpha preamble, before subsections"), alpha)
    assert(!alpha.contains("First leaf"), alpha)
    val one: String = html("chunked/Alpha-One.html")
    assert(one.contains("First leaf"), one)
    assert(!one.contains("Second leaf"), one)
    val two: String = html("chunked/Alpha-Two.html")
    assert(two.contains("Second leaf"), two)
    val beta: String = html("chunked/Beta.html")
    assert(beta.contains("Beta has no children"), beta)
  }

  test("AsciiDoc book: checklist IR, table, footnote, citation, glossary") {
    val page: String = html("book.html")
    assert(page.contains("""class="task-list""""), page)
    assert(page.contains("open the chapter"), page)
    assert(page.contains("done the chapter"), page)
    assert(!page.contains("""class="checklist""""), page)
    assert(page.contains("<table"), page)
    assert(page.contains("""class="footnote-ref""""), page)
    assert(page.contains("AsciiDoc footnote body"), page)
    assert(page.contains("Clinging AsciiDoc"), page)
    assert(page.contains("""</strong><span class="footnote-ref""""), page)
    assert(page.contains("""href="#bibl-knuth79""""), page)
    assert(page.contains("""id="bibl-knuth79""""), page)
    assert(page.contains("""id="knuth-book""""), page)
    assert(page.contains("""href="#knuth-book""""), page)
    assert(page.contains("Art of Computer Programming"), page)
    assert(page.contains("""class="citation-ref""""), page)
    assert(page.contains("""class="citation-tip""""), page)
    assert(page.contains("glossary-item"), page)
    assert(page.contains("""id="posuk""""), page)
    assert(page.contains("verse"), page)
    assert(page.contains("""class="glossary-ref""""), page)
    assert(page.contains("""class="callout""""), page)
    assert(page.contains("""class="callout-list""""), page)
    assert(page.contains("Library import"), page)
    assert(page.contains("""class="admonition""""), page)
    assert(page.contains("""data-type="note""""), page)
    assert(page.contains("Auxiliary information"), page)
    assert(page.contains("""class="aside""""), page)
    assert(page.contains("Auxiliary content"), page)
    assert(page.contains("""class="quote""""), page)
    assert(page.contains("""class="quote-title""""), page)
    assert(page.contains("A title"), page)
    assert(page.contains("A little rebellion"), page)
    assert(page.contains("""class="quote-attribution""""), page)
    assert(page.contains("Jefferson"), page)
    assert(page.contains("Papers"), page)
    assert(page.contains("<del"), page)
    assert(page.contains("obsolete phrase"), page)
    assert(!page.contains("line-through"), page)
    assert(page.contains("""class="figure""""), page)
    assert(page.contains("pixel.svg"), page)
    assert(page.contains("A figure caption"), page)
    assert(!page.contains("imageblock"), page)
    assert(page.contains("""class="pdf-embed""""), page)
    assert(page.contains("sample.pdf"), page)
    assert(page.contains("<video"), page)
    assert(page.contains("clip.mp4"), page)
    assert(!page.contains("videoblock"), page)
  }

  test("HTML about: table, task-list IR, glossary, header nav, citation IR") {
    val page: String = html("about.html")
    assert(page.contains("<table"), page)
    assert(page.contains("""class="task-list""""), page)
    assert(page.contains("html-open"), page)
    assert(page.contains("html-done"), page)
    assert(page.contains("""id="html-term""""), page)
    assert(page.contains("defined in HTML"), page)
    assert(page.contains("""class="glossary-ref""""), page)
    assert(page.contains("""href="#bibl-knuth79""""), page)
    assert(page.contains("""id="bibl-knuth79""""), page)
    assert(page.contains("""class="aside""""), page)
    assert(page.contains("already"), page)
    assert(page.contains("""class="quote""""), page)
    assert(page.contains("HTML quotation"), page)
    assert(page.contains("""class="quote-attribution""""), page)
    assert(page.contains("Work"), page)
    assert(page.contains("<del"), page)
    assert(page.contains("HTML struck"), page)
    assert(page.contains("HTML footnote body"), page)
    assert(page.contains("""</em><span class="footnote-ref""""), page)
    assert(page.contains("""class="figure""""), page)
    assert(page.contains("pixel.svg"), page)
    assert(page.contains("HTML figure"), page)
    assert(page.contains("""class="pdf-embed""""), page)
    assert(page.contains("sample.pdf"), page)
    assert(page.contains("<video"), page)
    assert(page.contains("clip.mp4"), page)
    val home: String = html("index.html")
    assert(home.contains("""href="/about.html""""), home)
  }

  test("TEI sample: endnote, table, glossary, code, and quote") {
    val page: String = html("tei-sample.html")
    assert(page.contains("""class="post-title p-name""""), page)
    assert(page.contains("TEI Sample"), page)
    assert(page.contains("TEI endnote body"), page)
    assert(page.contains("""class="footnote-ref""""), page)
    assert(page.contains("Clinging note"), page)
    assert(page.contains("""this<span class="footnote-ref""""), page)
    assert(page.contains("""</hi><span class="footnote-ref""""), page)
    assert(page.contains("<table"), page)
    assert(page.contains(">A<") || page.contains(">A</"), page)
    assert(page.contains("glossary-item"), page)
    assert(page.contains("""id="posuk""""), page)
    assert(page.contains("verse"), page)
    assert(page.contains("""class="glossary-ref""""), page)
    assert(page.contains("language-scala"), page)
    assert(page.contains("xs.map(f)"), page)
    assert(page.contains("""class="quote""""), page)
    assert(page.contains("A TEI quotation"), page)
    assert(page.contains("""class="quote-attribution""""), page)
    assert(page.contains("Jefferson"), page)
    assert(page.contains("Papers"), page)
    assert(page.contains("<del"), page)
    assert(page.contains("TEI struck"), page)
    assert(page.contains("""class="figure""""), page)
    assert(page.contains("pixel.svg"), page)
    assert(page.contains("A TEI figure"), page)
    assert(page.contains("""class="bibliography""""), page)
    assert(page.contains("""id="knuth79""""), page)
    assert(page.contains("""id="lamport94""""), page)
    assert(page.contains("""href="#knuth79""""), page)
    assert(page.contains("Knuth 1979"), page)
    assert(page.contains("""class="citation-ref""""), page)
    assert(page.contains("""class="citation-tip""""), page)
    assert(page.contains("lamport94"), page)
    assert(page.contains("""href="#bibl-knuth79""""), page)
    assert(page.contains("""id="bibl-knuth79""""), page)
    assert(page.contains("""class="csl-entry""""), page)
  }

  test("DocBook sample: title, section, paragraph") {
    val page: String = html("docbook-sample.html")
    assert(page.contains("DocBook Sample"), page)
    assert(page.contains("A DocBook paragraph"), page)
    assert(page.contains("Introduction"), page)
    assert(page.contains("""class="section""""), page)
    assert(page.contains("<p"), page)
    assert(!page.contains("<para"), page)
    assert(page.contains("DocBook footnote body"), page)
    assert(page.contains("""class="footnote-ref""""), page)
    assert(page.contains("Clinging note"), page)
    assert(page.contains("""this<span class="footnote-ref""""), page)
    assert(page.contains("""</em><span class="footnote-ref""""), page)
    assert(page.contains("<table"), page)
    assert(page.contains(">A<") || page.contains(">A</"), page)
    assert(page.contains("glossary-item"), page)
    assert(page.contains("""id="posuk""""), page)
    assert(page.contains("verse"), page)
    assert(page.contains("""class="glossary-ref""""), page)
    assert(page.contains("language-scala"), page)
    assert(page.contains("xs.map(f)"), page)
    assert(page.contains("""class="quote""""), page)
    assert(page.contains("A DocBook quotation"), page)
    assert(page.contains("""class="quote-attribution""""), page)
    assert(page.contains("Jefferson"), page)
    assert(page.contains("<del"), page)
    assert(page.contains("DocBook struck"), page)
    assert(page.contains("""class="figure""""), page)
    assert(page.contains("pixel.svg"), page)
    assert(page.contains("A DocBook figure"), page)
    assert(page.contains("""class="admonition""""), page)
    assert(page.contains("Auxiliary information"), page)
    assert(page.contains("""class="aside""""), page)
    assert(page.contains("From DocBook"), page)
    assert(page.contains("""class="callout""""), page)
    assert(page.contains("Library import"), page)
    assert(page.contains("<video"), page)
    assert(page.contains("clip.mp4"), page)
    assert(page.contains("""class="bibliography""""), page)
    assert(page.contains("""id="knuth79""""), page)
    assert(page.contains("""id="lamport94""""), page)
    assert(page.contains("""href="#knuth79""""), page)
    assert(page.contains("Knuth 1979"), page)
    assert(page.contains("""class="citation-ref""""), page)
    assert(page.contains("""class="citation-tip""""), page)
    assert(page.contains("lamport94"), page)
    assert(page.contains("""href="#bibl-knuth79""""), page)
    assert(page.contains("""id="bibl-knuth79""""), page)
    assert(page.contains("""class="csl-entry""""), page)
  }

  test("dated post is published and listed") {
    val post: String = html("2026/08/01/hello.html")
    assert(post.contains("Hello from a post"), post)
    assert(post.contains("""href="/notes.html""""), post)
    val posts: String = html("posts.html")
    assert(posts.contains("/2026/08/01/hello.html"), posts)
    assert(posts.contains("/2026/07/01/earlier.html"), posts)
    assert(!posts.contains("/2026/06/01/oldest.html"), posts)
    assert(posts.contains("""class="pagination""""), posts)
    assert(posts.contains("""class="post-excerpt""""), posts)
    assert(posts.contains("Greeting from the newest fixture post"), posts)
    val posts2: String = html("posts/2.html")
    assert(posts2.contains("/2026/06/01/oldest.html"), posts2)
    assert(!posts2.contains("/2026/08/01/hello.html"), posts2)
    assert(!posts2.contains("""class="post-excerpt""""), posts2)
    val sitemap: String = html("sitemap.xml")
    assert(sitemap.contains("/posts.html"), sitemap)
    assert(sitemap.contains("/posts/2.html"), sitemap)
    val tags: String = html("tags.html")
    assert(tags.contains("fixture"), tags)
  }

  test("Playwright PDF of glossary: page count, named dest, text") {
    val pdf: File = File(targetDirectory, "glossary.pdf")
    assert(pdf.isFile, s"missing glossary.pdf under $targetDirectory")
    val document = Loader.loadPDF(pdf)
    try
      val pages: Int = document.getNumberOfPages
      assert(pages >= 1, s"expected at least one page, got $pages")
      val text: String = PDFTextStripper().getText(document).replaceAll("\\s+", " ")
      assert(text.contains("a verse"), text)
    finally
      document.close()
    val dests: Map[String, Int] = PdfNamedDestinations.pageByName(pdf)
    assert(dests.get("posuk").exists(_ >= 1), dests)
  }

  test("sitemap, robots, and feed mention generated pages") {
    val sitemap: String = html("sitemap.xml")
    assert(sitemap.contains("http://fixture.test/index.html"), sitemap)
    assert(sitemap.contains("http://fixture.test/notes.html"), sitemap)
    val robots: String = html("robots.txt")
    assert(robots.contains("http://fixture.test/sitemap.xml"), robots)
    val feed: String = html("feed.xml")
    assert(feed.contains("hello"), feed)
    assert(feed.contains("Greeting from the newest fixture post"), feed)
  }

  test("pages advertise the Atom feed") {
    val page: String = html("index.html")
    assert(page.contains("""rel="alternate""""), page)
    assert(page.contains("""type="application/atom+xml""""), page)
    assert(page.contains("""href="http://fixture.test/feed.xml""""), page)
    assert(page.contains("""title="Site Publisher Fixture""""), page)
    val feed: String = html("feed.xml")
    assert(feed.contains("Site Publisher"), feed)
    assert(feed.contains("https://github.com/dubinsky/site-publisher"), feed)
  }

  test("home page SEO: site title, description, canonical, WebSite") {
    val page: String = html("index.html")
    assert(page.contains("<title>Site Publisher Fixture</title>"), page)
    assert(page.contains("""name="generator""""), page)
    assert(page.contains("Site Publisher (https://github.com/dubinsky/site-publisher)"), page)
    assert(page.contains("""name="description""""), page)
    assert(page.contains("End-to-end fixture for site-publisher tests"), page)
    assert(page.contains("""rel="canonical""""), page)
    assert(page.contains("""href="http://fixture.test/index.html""""), page)
    assert(page.contains("""property="og:type""""), page)
    assert(page.contains("""content="website""""), page)
    assert(page.contains("""property="og:locale""""), page)
    assert(page.contains("""content="en_US""""), page)
    assert(page.contains("""name="twitter:card""""), page)
    assert(page.contains("""content="summary""""), page)
    assert(page.contains(""""@type":"WebSite""""), page)
    assert(page.contains("""itemtype="http://schema.org/WebSite""""), page)
  }

  test("post SEO: titled with site, article type, BlogPosting") {
    val page: String = html("2026/08/01/hello.html")
    assert(page.contains("<title>hello | Site Publisher Fixture</title>"), page)
    assert(page.contains("""property="og:type""""), page)
    assert(page.contains("""content="article""""), page)
    assert(page.contains("""property="article:published_time""""), page)
    assert(page.contains("2026-08-01"), page)
    assert(page.contains(""""@type":"BlogPosting""""), page)
    assert(page.contains("""itemtype="http://schema.org/BlogPosting""""), page)
    assert(page.contains("""href="http://fixture.test/2026/08/01/hello.html""""), page)
  }

  test("ordinary page SEO is WebPage") {
    val page: String = html("notes.html")
    assert(page.contains("<title>notes | Site Publisher Fixture</title>"), page)
    assert(page.contains(""""@type":"WebPage""""), page)
    assert(page.contains("""itemtype="http://schema.org/WebPage""""), page)
  }
